### ISSUE TITLE
Implement pika per consumer limit

### ISSUE THREAD

**Issue by mennohie** [mennohie/wdm24-team9#19]
Use `channel.basicQos(n)` like in https://stackoverflow.com/questions/53552041/pika-single-queue-with-multiple-consumers

**Comment by janvandermeulen** [comment]
Closes with PR \(https://github.com/mennohie/wdm24-team9/pull/27)

**Comment by janvandermeulen** [comment]
I closed it because there is no need to do a consumer limit if each consumer gets its own queue in the new implementation.
