### ISSUE TITLE
RabbitMQ queue should stay persistent after crash or restart

### ISSUE THREAD

**Issue by mennohie** [mennohie/wdm24-team9#22]

**Comment by HarmenKroon** [comment]
https://www.rabbitmq.com/docs/queues#durability
> Durable queues will be recovered on node boot, including messages in them published as persistent.

https://www.rabbitmq.com/docs/publishers#message-properties

Property | Type | Description | Required?
-- | -- | -- | --
Delivery mode | Enum (1 or 2) | 2 for "persistent", 1 for "transient". Some client libraries expose this property as a boolean or enum. | Yes
