### ISSUE TITLE
Order service crash after connection timeout

### ISSUE THREAD

**Issue by HarmenKroon** [mennohie/wdm24-team9#39]
> File "/home/flask-app/app.py", line 136, in <module>
> 2024-06-02 18:06:55     publisher = create_connection()
> 2024-06-02 18:06:55                 ^^^^^^^^^^^^^^^^^^^
> 2024-06-02 18:06:55   File "/home/flask-app/app.py", line 132, in create_connection
> 2024-06-02 18:06:55     raise Exception("Failed to connect to RabbitMQ after several attempts")
> 2024-06-02 18:06:55 Exception: Failed to connect to RabbitMQ after several attempts

Can be fixed just like the connection loops in rabbitmq-consumer

**Comment by mennohie** [comment]
we could just add more retries, loop is already implemented

or just make the loop infinite
