### ISSUE TITLE
Write down your contributions

### ISSUE THREAD

**Issue by HarmenKroon** [mennohie/wdm24-team9#5]
According to the project description we need a `contributions.txt` file:

> `contributions.txt` should be a file at the top-level directory of your repository where each member describes (in a sentence) what they have contributed to the project (e.g., code, architecture, documentation, experiments, psychological support, beer, cookies, etc.)

**Comment by janvandermeulen** [comment]
Added the contributions.txt to the repo, please add something if you feel like I missed something.
